### ISSUE TITLE
Where did you get jaco v0.9.5?

### ISSUE THREAD

**Issue by adamk33n3r** [maximonster/MaxHitSound#1]
Heya! I was just looking at your plugin because I wanted to add mp3 functionality to mine and I saw you were using jaco mp3 player but online all I can see is v0.9.3 and v0.9.4. Where did you get a v0.9.5?

**Comment by maximonster** [comment]
Apparently I found it in the firebeats plugin https://github.com/RKGman/fire-beats/tree/master/libs

**Comment by adamk33n3r** [comment]
Ha, the rabbit trail continues. I just want to make sure I'm using official code and nothing jank. So weird! Thanks.
